name: test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cd ./test; ./config.sh;
    - name: Run
      run: cd ./test; ./sudo.source_test.sh;

