name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure test 
      run: cd ./test; ./config.sh
    - name: run the test.
      run: cd ./test; ./sudo.source_test.sh
